server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true

store:
  security:
    jwt:
      secret: store-cloud-auth-refresh-secret-key-2026-demo

knife4j:
  gateway:
    enabled: true
    strategy: manual
    tags-sorter: alpha
    operations-sorter: alpha
    routes:
      - name: Auth Service
        service-name: auth-service
        url: /api/auth/v3/api-docs
        context-path: /api
        order: 1
      - name: User Service
        service-name: user-service
        url: /api/user/v3/api-docs
        context-path: /api
        order: 2
      - name: Product Service
        service-name: product-service
        url: /api/product/v3/api-docs
        context-path: /api
        order: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway